# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18mB1XUwSswTaDtyc2X2MET-CJU32GHoO

NOMOR 1
"""

def divisible (m,n):
    if (m % n == 0):
        return True

    else :
        return False

print(divisible(22,5))
print(divisible(80,20))

"""NOMOR 2"""

def main_menu():
    print("Welcome In MPENG RESTO")
    print('==========================')
    print("========MAIN MENU=========")
    print(" 1. Soup and salad        ")
    print(" 2. Pasta with meat sauce ")
    print(" 3. Chef’s special        ")
    print('==========================')
    
    number = input("Which number would you like to order ? ")
    if number == '1':
        print('One Soup and salad coming right up!')
    elif number == '2':
        print('One Pasta with meat sauce coming right up!')
    elif number == '3':
        print('One Chef’s special coming right up!')
    else :
        print('Sorry, that is not a valid choice.')
# main program
if __name__=='__main__':
    main_menu()

"""NOMOR 3"""

def rand_divis_3 ():
    x=int(input("Masukkan bilangan: "))
    
    if (x % 3 == 0):
        return True

    else :
        return False
print(rand_divis_3())

"""NOMOR 4"""

1 != 1

def not_equal(x,y):
    if (x != y):
        return True
    else :
        return False
print(not_equal(3,2))

def not_equal(x,y):
    if (not (x == y)):
        return True
    else :
        return False
print(not_equal(3,2))

"""NOMOR 5"""

def ask_name():
    name = input("Enter your name: ")

ask_name()
print("Your name is", name)

name = input("Enter your name: ")
print("Your name is", name)
print ('atau')
def ask_name(name):
    print("Your name is", name)
ask_name("Emuu")